---
- name: Playbook to copy files
  become: true
  connection: ssh
  hosts: all
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /home/ansible/jenkins_playbook/demojava.jar
        dest: /home/ansible/jenkins-play
        owner: root
        group: root
        mode: '0644'
